//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SST_F350.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_CSTRING_OK                  102
#define IDD_SST_F350_DIALOG             102
#define IDS_ESTRING103                  103
#define IDS_ESTRING_ABOUT1              104
#define IDS_ESTRING_ABOUT2              105
#define IDS_ESTRING_DL1                 106
#define IDS_ESTRING_DL2                 107
#define IDS_ESTRING_DL3                 108
#define IDS_ESTRING_BROWSE              109
#define IDS_ESTRING_START               110
#define IDS_ESTRING_DL4                 111
#define IDS_ESTRING_DL5                 112
#define IDS_ESTRING_DL6                 113
#define IDS_ESTRING_DL7                 114
#define IDS_ESTRING_NV1                 115
#define IDS_ESTRING_NV2                 116
#define IDS_ESTRING_NV3                 117
#define IDS_ESTRING_NV4                 118
#define IDS_ESTRING_NV5                 119
#define IDS_ESTRING_MAIN1               120
#define IDS_ESTRING_MAIN2               121
#define IDS_ESTRING_MAIN3               123
#define IDS_ESTRING_MAIN4               124
#define IDS_ESTRING_MAIN5               125
#define IDS_ESTRING_MAIN6               126
#define IDS_ESTRING_MAIN7               127
#define IDR_MAINFRAME                   128
#define IDS_ESTRING_ABOUT               128
#define IDD_DIALOG_DL                   129
#define IDS_ESTRING_EXIT                129
#define IDD_DIALOG_NV                   130
#define IDS_ESTRING_TABDL               130
#define IDS_ESTRING_TABNV               131
#define IDB_LOGO                        132
#define IDS_STRING132                   132
#define IDB_RUNNING                     133
#define IDS_STRING133                   133
#define IDB_SEARCHING                   134
#define IDS_CSTRING_DL1                 134
#define IDB_READY                       135
#define IDS_CSTRING_DL2                 135
#define IDB_FAIL                        136
#define IDS_CSTRING_DL3                 136
#define IDB_PASS                        137
#define IDS_CSTRING_BROWSE              137
#define IDR_PORT_DISCONNECT             138
#define IDS_CSTRING_START               138
#define IDR_PORT_CONNECT                139
#define IDS_CSTRING_DL4                 139
#define IDS_CSTRING_DL5                 140
#define IDS_CSTRING_DL6                 141
#define IDS_CSTRING_DL7                 142
#define IDS_CSTRING_NV1                 143
#define IDS_CSTRING_NV2                 144
#define IDB_LOGOM                       144
#define IDS_CSTRING_NV3                 145
#define IDD_DIALOG_REG                  145
#define IDS_CSTRING_NV4                 146
#define IDS_CSTRING_NV5                 147
#define IDS_CSTRING_MAIN1               148
#define IDI_ICON_SDLOAD                 148
#define IDS_CSTRING_MAIN2               149
#define IDS_CSTRING_MAIN3               150
#define IDI_ICON_REPAIR                 150
#define IDS_CSTRING_MAIN4               151
#define IDI_ICON_DOWNLOAD               151
#define IDS_CSTRING_MAIN5               152
#define IDS_CSTRING_MAIN6               153
#define IDD_FLASH_BACKUP                153
#define IDS_CSTRING_MAIN7               154
#define IDS_CSTRING_ABOUT               155
#define IDD_DIALOG_REFUR                155
#define IDS_CSTRING_EXIT                156
#define IDD_DIALOG_DMU                  156
#define IDS_CSTRING_TABDL               157
#define IDS_CSTRING_TABNV               158
#define IDC_BUTTON_ABOUT                1000
#define IDC_BUTTON_EXIT                 1001
#define IDC_COMBO_BOUND                 1003
#define IDC_COMBO_COM                   1004
#define IDC_TAB_PAGE                    1006
#define IDC_PROGRESS                    1007
#define IDC_STATIC_PROGRESS             1008
#define IDC_STATIC_INFO                 1009
#define IDC_STATIC_CBSELECT             1010
#define IDC_STATIC_HANDSELECT           1011
#define IDC_STATIC_PORTINFO             1012
#define IDC_STATIC_COM                  1013
#define IDC_STATIC_CSELECT              1014
#define IDC_STATIC_BSELECT              1015
#define IDC_STATIC_BSELECT2             1016
#define IDC_NVRADIO1                    1017
#define IDC_NVRADIO2                    1018
#define IDC_BUTTON_BKB                  1019
#define IDC_BUTTON_RSB                  1020
#define IDC_BUTTON_BKS                  1021
#define IDC_BUTTON_RSS                  1022
#define IDC_EDIT_USERFILE_PATH          1023
#define IDC_EDIT_NVFILE_PATH            1025
#define IDC_BUTTON_REG                  1026
#define IDC_BUTTON2                     1027
#define IDC_BUTTON3                     1028
#define IDC_STATIC_BMP                  1031
#define IDC_STATIC_PORT                 1032
#define IDC_BUTTON_START                1033
#define IDC_STATIC_NVFILE               1034
#define IDC_STATIC_NVPATH               1035
#define IDC_EDIT_COMPUTERID             1042
#define IDC_EDIT_DLTIMES                1044
#define IDC_STATIC_SPC                  1045
#define IDC_STATIC_LEFTTIME             1046
#define IDC_EDIT_RUNTIMES               1047
#define IDC_EDIT_CODE                   1048
#define IDC_BUTTON_CANCEL               1049
#define IDC_SPIN1                       1050
#define IDC_BUTTON_HELP                 1052
#define IDC_LOCK_CHECK                  1053
#define IDC_RADIO1                      1054
#define IDC_RADIO_UNRES                 1054
#define IDC_RADIO_NAM                   1054
#define IDC_RADIO2                      1055
#define IDC_RADIO_RES                   1055
#define IDC_EDIT2                       1056
#define IDC_LOCK_FILE                   1056
#define IDC_EDIT_START                  1056
#define IDC_CHECK_USER                  1057
#define IDC_BUTTON_BROWSE               1058
#define IDC_LOCKFILE_PATH               1059
#define IDC_RADIO3                      1060
#define IDC_EDIT_PATH                   1061
#define IDC_COMBO_SIZE                  1062
#define IDC_EDIT_END                    1063
#define IDC_BUTTON_OK                   1065
#define IDC_STATIC_SIZES                1066
#define IDC_STATIC_SIZEE                1067
#define IDC_RADIO4                      1069
#define IDC_RADIO5                      1070
#define IDC_BUTTON_REFRESH              1071
#define IDC_EDIT_SPC                    1072
#define IDC_BUTTON_REFUR                1073
#define IDC_EDIT_SPCCODE                1074
#define IDC_EDIT_DMU_PATH               1075
#define IDC_RADIO_BACKUP_ESN            1079
#define IDC_RADIO_RF                    1080
#define IDC_RADIO_BACKUP_NULL           1081
#define IDC_RADIO_RESERVENV             1082
#define IDC_CHECK_BOOT                  1083
#define IDC_BUTTON_SET                  1084
#define IDC_EDIT_SPC2                   44444

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
