
#ifndef MYMEDIA_RES_H
#define MYMEDIA_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MYMEDIA_RES_FILE "mymedia.bar"

#define IDS_TITLE		1
#define IDS_ENTER		2
#define IDS_HELP		3
#define IDS_ABOUT		4
#define IDS_ABOUT_DATA		5
#define IDS_OK		6
#define IDB_DOG		5001
#define IDB_HELP		5002


#endif  // MYMEDIA_RES_H
