
#ifndef MYIMAGE_RES_H
#define MYIMAGE_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MYIMAGE_RES_FILE "myimage.bar"

#define IDS_TITLE		1
#define IDS_BITMAP		2
#define IDS_ANIMATION		3
#define IDS_BCI		4
#define IDB_TIMER		5001
#define IDB_BCI		5002


#endif  // MYIMAGE_RES_H
