
#ifndef EXDIAG_RES_H
#define EXDIAG_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define EXDIAG_RES_FILE "ExDiag.bar"

#define IDS_TEXT		1
#define IDS_LIST_1		2
#define IDS_LIST_2		3
#define IDS_LIST_3		4
#define IDS_MENU		5
#define IDS_MENU_1		6
#define IDS_MENU_2		7
#define IDS_MENU_3		8
#define IDS_MENU_TITLE		9
#define IDS_TEXT_TITLE		10
#define IDS_SOFT_1		11
#define IDS_SOFT_2		12
#define IDS_STATIC		13
#define IDB_DIR		5001
#define IDB_ICON1		5002
#define IDB_ICON2		5003
#define IDD_ITEM_STATIC		7001
#define IDD_LISTITEM1		8001
#define IDD_LISTITEM2		8002
#define IDD_LISTITEM3		8003
#define IDD_LIST		7002
#define IDD_MENU_ITEM1		8004
#define IDD_MENU_ITEM2		8005
#define IDD_MENU_ITEM3		8006
#define IDD_MENU		7003
#define IDD_DEMO		6001


#endif  // EXDIAG_RES_H
