
#ifndef MYMENU_RES_H
#define MYMENU_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MYMENU_RES_FILE "mymenu.bar"

#define IDS_ENTER		1
#define IDS_HELP		2
#define IDS_ABOUT		3
#define IDS_TITLE		4
#define IDB_ENTER		5001
#define IDB_HELP		5002
#define IDB_ABOUT		5003


#endif  // MYMENU_RES_H
