
#ifndef FK_RES_H
#define FK_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define FK_RES_FILE "fk.bar"

#define IDS_TITLE		1
#define IDB_PIC		5001


#endif  // FK_RES_H
