
#ifndef MYDISPLAY_RES_H
#define MYDISPLAY_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MYDISPLAY_RES_FILE "mydisplay.bar"

#define IDS_TEST		1


#endif  // MYDISPLAY_RES_H
