
#ifndef EXRSA_RES_H
#define EXRSA_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define EXRSA_RES_FILE "ExRsa.bar"

#define IDS_HELLO		1
#define IDS_DEMO		2


#endif  // EXRSA_RES_H
