
#ifndef GAMEDEMO_RES_H
#define GAMEDEMO_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define GAMEDEMO_RES_FILE "GameDemo.bar"

#define IDS_MENU_BEGIN		1
#define IDS_MENU_LOAD		2
#define IDS_MENU_HELP		3
#define IDS_MENU_VOL_ON		4
#define IDS_MENU_VOL_OFF		5
#define IDS_MENU_EXIT		6
#define IDS_MENU_SELECT		7


#endif  // GAMEDEMO_RES_H
