
#ifndef MYSTATIC_RES_H
#define MYSTATIC_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MYSTATIC_RES_FILE "mystatic.bar"

#define IDS_TITLE		1
#define IDS_TEXT		2
#define IDS_PIC		3
#define IDS_NO_SCROLL		4
#define IDS_TEXT_CONTENT		5
#define IDS_TEXT_TITLE		6
#define IDS_PIC_TITLE		7
#define IDS_NOSCROLL_TITLE		8
#define IDS_NOSCROLL_CONTENT		9
#define IDB_BITMAP		5001


#endif  // MYSTATIC_RES_H
