
#ifndef IVOCUSE_RES_H
#define IVOCUSE_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define IVOCUSE_RES_FILE "ivocuse.bar"

#define IDSMAIN_TITLE		1
#define IDSMAIN_STREAM		2
#define IDSMAIN_INFO		3
#define IDSMAIN_EXIT		4
#define IDSSOFT_ACTIVATE		5
#define IDSSOFT_DEACTIVATE		6
#define IDSSOFT_EXIT		7
#define IDS_STREAM		8
#define IDS_PAUSE		9
#define IDS_ERROR		10
#define IDS_ABOUT		11
#define IDS_BACK		12


#endif  // IVOCUSE_RES_H
