
#ifndef ANI_RES_H
#define ANI_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define ANI_RES_FILE "ani.bar"

#define IDS_TITLE		1
#define IDB_BMP_GIRL		5001


#endif  // ANI_RES_H
