
#ifndef MYTEXT_RES_H
#define MYTEXT_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MYTEXT_RES_FILE "mytext.bar"

#define IDS_SINGLE		1
#define IDS_MULTI		2
#define IDS_TITLE		3
#define IDS_INPUT_INFO		4
#define IDS_DISPLAY		5
#define IDS_OK		6
#define IDS_TITLE_ADDED		7
#define IDS_INPUTMODE		8
#define IDS_PINYIN		9
#define IDS_NUMBERS		10
#define IDS_ENGLISH		11
#define IDS_T9		12
#define IDS_STROKE		13
#define IDS_EZTEXT		14
#define IDS_RAPID		15
#define IDS_SYMBOLS		16


#endif  // MYTEXT_RES_H
