
#ifndef EXSOUND_RES_H
#define EXSOUND_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define EXSOUND_RES_FILE "ExSound.bar"

#define IDM_BEGIN		5001


#endif  // EXSOUND_RES_H
