
#ifndef IFILE_RES_H
#define IFILE_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define IFILE_RES_FILE "ifile.bar"

#define IDS_ITEM		20
#define IDS_ITEM_2		30
#define IDB_BMP		10


#endif  // IFILE_RES_H
